config/routes.rb
Tweetbay::Application.routes.draw do
  resources :users
  resources :users
  resources :contents
  resources :sessions, only: [:create, :new, :destroy]
  resources :image_contents, only: [:create]

  root "contents#index"

  get "splash", :to => "splash#index", :as => "splash"
  get "howitworks", :to => "splash#howitworks", :as => "howitworks"
  get "aboutus", :to => "splash#aboutus", :as => "aboutus"

  get "onboard", :to => "contents#onboard", :as => "onboard"
  get "orders", :to => "contents#orders", :as => "orders"

  get "logout", :to => "sessions#destroy", :as => "logout"
  get "login", :to => "sessions#new", :as => "login"
  get "signup", :to => "users#new", :as => "signup"
  get "profile", :to => "users#profile", :as => "profile"
  get "post", :to => "contents#new", :as => "post"

  get "auth/twitter", :as => "twitter_auth"
  get "auth/:provider/callback", :to => "sessions#create"

  post '/contents/create_reply', controller: 'contents', action: 'create_reply'
  

end

app/models/content.rb
class Content < ActiveRecord::Base
  has_ancestry
  has_one :image, dependent: :destroy
  
  before_save { |content| content.title = title.titleize }

  default_scope { order('created_at') }

  validates :description, presence: true

  belongs_to :user

  def permitted_actions(myuser)
    action_list = []
    if myuser == user
      action_list << :edit
      action_list << :delete
    else
      unless ancestry?
        action_list << :report
        action_list << :thank
      end
    end
    return action_list
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  respond_to :js, :html, :json
  before_filter :require_login

  def new
    @no_turbo = true
    @content = Content.new
    @content.parent_id = params[:parent_id]
    
    respond_with @content
  end

  def create
    @content = Content.new(content_params)
    @content.user_id = current_user.id

    # TODO: code this later to allow comments and follow up content.
    @content.ancestry = params[:content][:parent_id].empty? ? nil : params[:content][:parent_id]
    if params[:content]['attachment']
      @image = Image.create!(:attachment => params[:content]['attachment'])
      @content.image = @image
    end
    

    if @content.save
      redirect_url = content_url(@content)
      flash[:success] = "New content posted!" if !request.xhr?

      unless params[:content][:parent_id].empty?
        redirect_url = content_url(@content.ancestry)
        flash[:success] = 'Comment Posted!' if !request.xhr?
      end
      
    end

    respond_with(@content, :location => redirect_url)
  end

  def index
    @active = "products"
    @user = current_user
    @contents = @user.contents.order('created_at DESC')
    if @contents.length == 0
      redirect_to onboard_url, data: { no_turbolink: true }
    else
      @contents = @contents.where({ancestry: nil})
      respond_with @content
    end
  end

  def orders
    @active = "orders"
  end

  def onboard
    @no_turbo = true
    @user = current_user
    @content = Content.new

    respond_with @content
  end

  def show
    @twitter_css = true
    @content = Content.find(params[:id])
    @reply = Content.new

    @user = current_user
    @embed_reply = true
    if @user != @content.user
      redirect_to contents_url
    else
      if @content.ancestry
        redirect_to content_url(@content.ancestry)
      end
      respond_with @content
    end
  end

  def edit
    @content = Content.find(params[:id])

    @title = @content.ancestry ? 'Edit Comment' : 'Edit Post'
    

    respond_with @content
  end

  def update
    @content = Content.find(params[:id])
    
    if @content.update_attributes(content_params)
      flash[:success] = "Post Updated!" if !request.xhr?
    end

    

    respond_with @content
  end

  def content_params
    params.require(:content).permit(
      :image_src, 
      :price,
      :description,
      :title
    )
  end

  def destroy
    @content = Content.find(params[:id])
    @content.destroy

    respond_with @content
  end

  def create_reply
    create
  end
  
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_actions.html.haml
.content-actions
  %ul
    
    
    - if content.children.length > 0
      %li #{@content.children.length} Comments
    
    
    - if content.permitted_actions(current_user).include?(:edit)
      %li
        = link_to "Edit", edit_content_url(content.id), 'data-no-turbolink' => true
    - if content.permitted_actions(current_user).include?(:delete)
      %li
        = link_to "Delete", content_url(content.id), :method => :delete, :remote => true
    - if content.permitted_actions(current_user).include?(:thank)
      %li
        = link_to "Thank", root_url, :class => "soft"
    - if content.permitted_actions(current_user).include?(:report)
      %li
        = link_to "Report", root_url, :class => "soft"
    

app/views/contents/_buypreview.html.haml
.buynow-container.modal-body.modal-hidden{ :id => "buyNowModal" }
  .buynow-left-column
    .buynow-productImageWrapper
      %img.buynow-largeImage{ :src => content.image_src, :alt => "Super awesome, one-of-a-kind t-shirt" }
    .buynow-altImageBox
      .buynow-altImageWrapper
        %img.buynow-smallImage{ :src => content.image_src, :alt => "Super awesome, one-of-a-kidn t-shirt" }
  .buynow-right-column
    .buynow-summary
      %h2 #{content.title}
      .buynow-byline
        Sold by #{current_user.name}
      .buynow-price
        - if content.price
          %span.buynow-currency #{number_to_currency(content.price, :unit => "$")}
        - else
          %span.buynow-currency #{number_to_currency(0, :unit => "$")}
        %span.buynow-shipping & shipping included
      .buynow-productInfo
        .buynow-label
          %a.buynow-labeltag.is-selected{ :href => "" } About
          %a.buynow-labeltag{ :href => "" } Shipping
          %a.buynow-labeltag{ :href => "" } Return
        .buynow-productInfoContent
          .buynow-contentText
            #{content.description}
          .buynow-contentText.is-hidden
            Shipping policy
          .buynow-contentText.is-hidden
            Sales terms
      - if false
        .buynow-variants 
          .buynow-variant
            %label.t1-label Color
            .select-box
              %select.t1-select
                %option{:value => "", :disabled => true, :selected => true}= "Select your option" 
                %option{:value => "Cyan", :selected => false}= "Cyan"
          .buynow-variant
            %label.t1-label Gender
            .select-box
              %select.t1-select
                %option{:value => "", :disabled => true, :selected => true}= "Select your option" 
                %option{:value => "Unisex", :selected => false}= "Unisex"
          .buynow-variant
            %label.t1-label Size
            .select-box
              %select.t1-select
                %option{:value => "", :disabled => true, :selected => true}= "Select your option" 
                %option{:value => "Medium", :selected => false}= "Medium"
                %option{:value => "Large", :selected => false}= "Large"
    .buynow-bottom
      .buynow-buyButtonArea
        %button.buynow-buyButton{ :type => "submit", :disabled => "disabled"}
          %span Buy now

app/views/contents/_comment.html.haml
.box-wrapper.comment
  .avatar
    = image_tag avatar_url(content.user), :class => "user-icon"
  .summary-content{:id => "comment_" + content.id.to_s}
    .text-line
      .line-name
        %span.passive-text 
          = link_to content.user.nickname, user_url(content.user)
        %span.time-text &#183; #{time_ago_in_words(content.created_at)} ago
    #{markdown content.description}

    - unless content.permitted_actions(current_user).empty?
      = render "actions", :content => content

app/views/contents/_post.html.haml
.embed-wrapper
  = form_for(@content, :html => { :class => 'embed-fields' }) do |f|
    %fieldset
      = f.text_field :title, :placeholder => "I want to sell...", :class => "req"
      = f.hidden_field :parent_id
      
      = f.text_area :description, :placeholder => "What are you selling and why is it awesome?", :class => "req", :rows => "6"
    .button-wrapper
      
      
      -#
        .file-input-wrapper
          %button.btn-file-input
            = image_tag("w_photo.png")
          = f.file_field :file
      
      
      = f.submit "Post", :class => "submit"
-#
  = direct_upload_form_for @uploader do |f|
    = f.file_field :attachment
    = f.submit "Upload Image"

app/views/contents/_productadd.html.haml
.add-product-wrap
  //.input-image#dropzone
  //  Add a photo or image
  %form#media-dropzone.dropzone{:action => "/image_contents", :enctype => "multipart/form-data"}
    .dz-message{"data-dz-message" => ""}
      .camera-icon
      %span Add a photo, image, or meme
    %input{:name => "authenticity_token", :type => "hidden", :value => form_authenticity_token}
    .fallback
      %input{:name => "media", :type => "file"}
  = form_for(@content, :html => { :class => 'form-fields' }) do |f|
    %fieldset
      = f.hidden_field :image_src, :id => "content-image", :value => ""
      = f.hidden_field :parent_id
      .input-row
        .col3
          = f.text_field :title, :placeholder => "What are you selling?", :class => "title req"
        .col1
          %span.dollar $
          = f.number_field :price, :placeholder => "0.00", :step => "any", :class => "price req"
      .input-row
        = f.text_area :description, :placeholder => "Tell us more.  Why will people love it? 😍", :class => "req"
      = f.submit "I'm done!", :class => "submit"

app/views/contents/_reply.html.haml
.box-wrapper.comment.reply-form
  .avatar
    = image_tag avatar_url(current_user), :class => "user-icon"
  .summary-content
    = form_for(@reply, :remote => true, :authenticity_token => true, :url => { :controller => "contents", :action => "create_reply" }, :html => { :class => 'inline-fields' }) do |f|
      = f.hidden_field :parent_id, :value => @content.id
      %fieldset
        = f.text_area :description, :placeholder => "Add a reply...", :class => "req", :id => "reply_field"
      .button-wrapper
        
        
        .file-input-wrapper
          %button.btn-file-input
            = image_tag("w_photo.png")
          = f.file_field :file
        
        
        = f.submit "Post", :class => "submit"

app/views/contents/_summary.html.haml
.box-wrapper
  .avatar
    = image_tag avatar_url(content.user), :class => "user-icon"
  .summary-content
    .text-line
      .line-name
        %span.passive-text #{content.user.nickname}
        %span.time-text &#183; #{time_ago_in_words(content.created_at)} ago
      %h2
        = link_to content.title, content_url(content.id)
    #{markdown( condenseString content.description)}
    - if strip_tags( markdown content.description ).length > 300
      .read-more
        = link_to "Read more...", content_url(content.id)

app/views/contents/create_chat_reply.js.haml
$('.chat-inner').append("#{j(render(partial: "contents/chatbox", locals: { content: @content }))}");

$('#chat_#{@content.id}').hide().fadeIn(500);

$('#reply_field').val("");

app/views/contents/create_reply.js.haml
$('.comments-inner').append("#{j(render('comment', content: @content))}");

$('#comment_#{@content.id}').hide().fadeIn(500);

$('#reply_field').val("");

app/views/contents/onboard.html.haml
.onboard-wrap
  %h1 Welcome!  Let's add your first product.
  %span (Don't worry, you can preview before posting.)
= render :partial => 'contents/productadd'

app/views/contents/orders.html.haml
.title-wrap
  %h1 You have no orders ... yet.

app/views/contents/show.html.haml
.modal-wrapper#modal-wrapper
  .inner
    = render "buypreview", :content => @content
    //%h1 Preview
.title-wrap
  %h1 #{@content.title} <span style="color: #aaa">(Draft)</span>
.preview-container
  .preview-left
    = render "preview", :content => @content
    .actions
      %a{:href => "#preview", :class => "modal-trigger"} preview
      = link_to "edit", edit_content_url(@content)
      = link_to "delete", @content, :method => :delete, :class => "urgent", data: { confirm: "Are you sure?" }
  .preview-right
    .detail-wrapper
      //%h2 Product Details
      .input-row
        %label Quantity Available:
        %input{:type => "text", :placeholder => "(optional)"}
      //.input-row
      //  %label Start Date
      //  %input{:type => "text", :placeholder => "now"}
      .input-row
        %label Shipping Fee:
        %input{:type => "text", :placeholder => "0.00"}
      .input-row
        %label End Date
        %input{:type => "text", :placeholder => "never", :class => "datepicker"}
      .input-center
        %input{:type => "submit", :id => "demo-trigger", :value => "Tweet it"}
      .demo-message
        Sorry, this is still a demo!  We'll be live soon, we promise :)