config/routes.rb
Tweetbay::Application.routes.draw do
  resources :users
  resources :users
  resources :contents
  resources :sessions, only: [:create, :new, :destroy]
  resources :image_contents, only: [:create]

  root "contents#index"

  get "splash", :to => "splash#index", :as => "splash"
  get "howitworks", :to => "splash#howitworks", :as => "howitworks"
  get "aboutus", :to => "splash#aboutus", :as => "aboutus"

  get "onboard", :to => "contents#onboard", :as => "onboard"
  get "orders", :to => "contents#orders", :as => "orders"

  get "logout", :to => "sessions#destroy", :as => "logout"
  get "login", :to => "sessions#new", :as => "login"
  get "signup", :to => "users#new", :as => "signup"
  get "profile", :to => "users#profile", :as => "profile"
  get "post", :to => "contents#new", :as => "post"

  get "auth/twitter", :as => "twitter_auth"
  get "auth/:provider/callback", :to => "sessions#create"

  post '/contents/create_reply', controller: 'contents', action: 'create_reply'
  

end

app/views/shared/_nav.html.haml
.header
  .inner
    .logo
      %a{:href => root_url} tweet<b>bay</b>
    .right
      .navmenu
        %ul
          %li
            .dropdown
              %ul
                %li
                  %a.subtle{:href => "#cash"} $0.00
                %li
                  = link_to "My Profile", profile_url
                %li
                  = link_to "Logout", logout_url
            %a{:href => "#", :id => "dropdown-toggle"}
              .user-menu
                %span.username @#{current_user.nickname}
                = image_tag avatar_url(current_user), :class => "tiny-icon"
          %li
            = link_to "Orders", orders_url, :class => ( defined?(@active) && @active == "orders" ? "active" : "" )
          %li
            = link_to "Products", contents_url, :class => ( defined?(@active) && @active == "products" ? "active" : "" )

app/views/shared/_sidebar.html.haml
%section{:class => "fixed-sidebar col3"}

  - if current_user
    %nav.title
      = link_to "Blub.io", root_url
    %nav
      = link_to "Discussions", root_url, :class => ( current_page?( root_url ) ? "active" : "") 
      = link_to "Profile", root_url
      = link_to "Sign Out", logout_url
  - else
    %ul
      %li 
        = link_to "Sign Up", new_user_url
      %li 
        = link_to "Log In", login_url