config/routes.rb
Tweetbay::Application.routes.draw do
  resources :users
  resources :users
  resources :contents
  resources :sessions, only: [:create, :new, :destroy]
  resources :image_contents, only: [:create]

  root "contents#index"

  get "splash", :to => "splash#index", :as => "splash"
  get "howitworks", :to => "splash#howitworks", :as => "howitworks"
  get "aboutus", :to => "splash#aboutus", :as => "aboutus"

  get "onboard", :to => "contents#onboard", :as => "onboard"
  get "orders", :to => "contents#orders", :as => "orders"

  get "logout", :to => "sessions#destroy", :as => "logout"
  get "login", :to => "sessions#new", :as => "login"
  get "signup", :to => "users#new", :as => "signup"
  get "profile", :to => "users#profile", :as => "profile"
  get "post", :to => "contents#new", :as => "post"

  get "auth/twitter", :as => "twitter_auth"
  get "auth/:provider/callback", :to => "sessions#create"

  post '/contents/create_reply', controller: 'contents', action: 'create_reply'
  

end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
    @splash_page = true
  end

  def howitworks
    @splash_page = true
    @twitter_css = true # Must include for twitter preview
    
    sample_params = {
      #:image_src => "https://upload.wikimedia.org/wikipedia/commons/6/60/Matterhorn_from_Domh%C3%BCtte_-_2.jpg", 
      :price => 1.00,
      :description => "Cool mountains",
      :title => "Swiss Alps"
    }
    @content = Content.new(sample_params)
  end
  
  def aboutus
    @splash_page = true
  end
end

app/views/splash/_header.html.haml
.header.sticky
  .inner
    .logo
      %a{:href => root_url} tweet<b>bay</b>
    %ul
      %li
        = link_to "Log in", twitter_auth_url, :class => "open-button"
      %li
        = link_to "Pricing", "#pricing", :class => ( defined?(aboutus) ? "active" : "" )
      %li
        = link_to "How It Works", "#howitworks", :class => ( defined?(howitworks) ? "active" : "" )

app/views/splash/_preview.html.haml
.preview-wrap
  .original-tweet-container.app
    .original-tweet
      .stream-item-header
        %a.account-group{ :href => "#twitter_account" }
          %img.avatar{ :src => image_url("twitter_avatar.png") }
          %strong.fullname Tweetbay
          %span.username
            %b @tweetbay
        %small.time
          %span
            PREVIEW
          %a.tweet-timestamp{ :href => "#detail-tweet" }
      .tweet-wrap
        %textarea{:type => "text", :placeholder => "Write a message to your followers here! 😎"}
        //%p.TweetTextSize Buy my new thing!
      .card-grid
        .card.image-card.top-card
          %span.helper
          %img{ :id => 'card-image', :src => @content.image_src, :alt => "No image :(" }
        .card.commerce-card.bottom-card
          .right
            %button{ :type => "submit", :class => "modal-trigger", "data-toggle" => "modal", "data-target" => "#buyNowModal" } Buy
          .left
            %h2.card-title{ :id => "card-title" } #{content.title}
            .buynow-byline
              - if content.price
                %span.buynow-price{ :id => "buynow-price" } #{number_to_currency(content.price, :unit => "$")}
              - else
                %span.buynow-price{ :id => "buynow-price" } #{number_to_currency(0, :unit => "$")}
              %span.buynow-merchant{ :id => "buynow-merchant" } Tweetbay
        .card-icons
          %img{ :src => image_url("twitter_icons.png"), :alt => "share" }

app/views/splash/aboutus.html.haml
= render "header", :aboutus => true
.about-wrap
  .title-wrap
    %h1 5% + 25¢ per transaction
  .about-container
    That's it. 
  .about-container
    No monthly fees, no processing fees, no refund fees.
  .start-link
    = link_to "Get Started", twitter_auth_url, :class => "button"

app/views/splash/howitworks.html.haml
= render "header", :howitworks => true
.title-wrap
  %h1 Your followers can buy without leaving Twitter.
  %span Try it out below.
.main-wrap
  = render partial: "contents/sample", :content => @content_sample
//= link_to "Get Started", twitter_auth_url, :class => "button"

app/views/splash/index.html.haml
= render "header"
%section.first
  .left
    .top-container
      //%h1 Got followers, hate fees?
      %h1.hero Sell anything in a tweet.
    .splash-container
      .info-wrap
        %h2 Your followers can now buy anything without leaving Twitter.
        = link_to "Connect with Twitter", twitter_auth_url, :class => "button"
        //%input{:type => "submit", :value => "Get Started"}
        .small
          Not on Twitter yet?  Share on Facebook or Pinterest too!
  .right
    .img-wrap
      %img{:src => image_url("splash-iphone.jpg")}
%section.second#howitworks
  .title
    %h1 Promoting your storefront is hard work.
    %span With <i>Tweetbay</i>, your followers can help you sell!
  .point
    .image
      %img{:src => image_url("infinity.svg")}
    .content
      %h2 Your product is everywhere
      %span Anyone can buy directly from your tweets or retweets!  It's also easy to share on Facebook and Pinterest.
  .point
    .image
      %img{:src => image_url("creditcard.svg")}
    .content
      %h2 One-click payments
      %span Your buyers don't have to re-enter payments on external sites.  Paying on Twitter is just one click!
  .point
    .image
      %img{:src => image_url("time.svg")}
    .content
      %h2 One minute setup
      %span Whether you're a hobbyist or professional, you can list anything in under a minute!
%section.third#pricing
  .title
    %h1 Simple low price.
  .subtitle
    %span 4% + 30¢ per transaction.  
    %p No hidden or monthly fees.
    = link_to "Get Started", twitter_auth_url, :class => "button"
  = javascript_include_tag "application"